import os
import sys
import pytest

# Add parent directory to sys.path to allow imports from src
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from dotenv import load_dotenv
from deepeval import assert_test
from deepeval.dataset import EvaluationDataset
from deepeval.test_case import LLMTestCase
from deepeval.metrics import FaithfulnessMetric, AnswerRelevancyMetric, ContextualPrecisionMetric, ContextualRecallMetric, ContextualRelevancyMetric
from src.extraction.parser import _parse_with_llamacloud, _build_pure_text_tree
from src.pipeline import vectorless_rag_no_loss
from llm_judge import bedrock_judge

load_dotenv()

def _build_tree() -> list[dict]:
    """Build the document tree from the same PDF used for test generation."""
    pdf_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "file", "acharya2019.pdf")
    )
    api_key = os.getenv("LLAMACLOUD_API_KEY")
    page_dicts = _parse_with_llamacloud(pdf_path, api_key)

    markdown_chunks = []
    for page_data in page_dicts:
        page_num = page_data["page"]
        markdown_chunks.append(f"--- Page {page_num} ---")
        markdown_chunks.append(page_data.get("md", ""))
    markdown_content = "\n".join(markdown_chunks)

    return _build_pure_text_tree(markdown_content)


# Build the tree once at import time (cached by LlamaCloud on subsequent runs)
GLOBAL_TREE = _build_tree()

# Load the synthetic dataset generated by generate_conversational.py
dataset = EvaluationDataset()
dataset.add_goldens_from_json_file(file_path="./test_data/rag_test_dataset.json")
MIN_QUALITY = 0.5
dataset.goldens = [
    g for g in dataset.goldens
    if g.additional_metadata is None
    or g.additional_metadata.get("synthetic_input_quality", 1.0) >= MIN_QUALITY
]
@pytest.mark.parametrize("golden", dataset.goldens)
def test_vectorless_rag_pipeline(golden):
    rag_output = vectorless_rag_no_loss(query=golden.input, tree=GLOBAL_TREE)
    test_case = LLMTestCase(
        input=golden.input,
        actual_output=rag_output["answer"],
        expected_output=golden.expected_output,
        retrieval_context=rag_output["retrieved_texts"]
    )

    metrics = [
        FaithfulnessMetric(threshold=0.6, model=bedrock_judge),
        AnswerRelevancyMetric(threshold=0.6, model=bedrock_judge),
        ContextualPrecisionMetric(threshold=0.6, model=bedrock_judge),
        ContextualRecallMetric(threshold=0.6, model=bedrock_judge),
        ContextualRelevancyMetric(threshold=0.6, model=bedrock_judge),
    ]

    assert_test(test_case, metrics)

    # Low ContextualRelevancyMetric → your Regex/BM25 retriever is pulling irrelevant chunks; tune your BM25 parameters or regex patterns.
    # Low ContextualPrecisionMetric → relevant chunks exist but are ranked too low; improve your scoring/ranking logic.
    # Low ContextualRecallMetric → your retriever is missing chunks needed to answer the question; increase top-K or improve coverage.
    # Low FaithfulnessMetric → your LLM is hallucinating beyond what was retrieved; consider prompt tuning.
    # Low AnswerRelevancyMetric → your LLM answer drifts from the question; improve your prompt template.
